apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wiz-webapi
  namespace: wizsuite-prod
spec:
  secretName: ind-prod-web.xyz.com
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'ind-prod-web.xyz.com'
