apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod
spec:
  source:
    repoURL: https://github.com/your-username/your-manifest-repo.git
    targetRevision: prod
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: wizsuite-prod
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

